export const StoreList = {
    tableName: 'storeList',
    tableFields: [
        { columnName: 'shopId', dataType: 'INTEGER' },
        { columnName: 'shopCode', dataType: 'VARCHAR(32)' },
        { columnName: 'shopName', dataType: 'NVARCHAR(250)' },
        { columnName: 'address', dataType: 'NVARCHAR(250)' },
        { columnName: 'latitude', dataType: 'FLOAT' },
        { columnName: 'longitude', dataType: 'FLOAT' },
        { columnName: 'locationTracking', dataType: 'INTEGER' },
        { columnName: 'auditDate', dataType: 'INTEGER' },
        { columnName: 'formatId', dataType: 'INTEGER' },
        { columnName: 'customerId', dataType: 'INTEGER' },
        { columnName: 'customerName', dataType: 'NVARCHAR(250)' },
        { columnName: 'account_Id', dataType: 'INTEGER' },
        { columnName: 'channelId', dataType: 'INTEGER' },
        { columnName: 'channelName', dataType: 'NVARCHAR(250)' },
        { columnName: 'ktc', dataType: 'INTEGER' },
        { columnName: 'minTime', dataType: 'INTEGER' },
        { columnName: 'checkTime', dataType: 'INTEGER' },
        { columnName: 'shiftName', dataType: 'NVARCHAR(50)' },
        { columnName: 'shiftCode', dataType: 'NVARCHAR(50)' },
        { columnName: 'timeIn', dataType: 'VARCHAR(5)' },
        { columnName: 'imageUrl', dataType: 'VARCHAR(105)' },
        { columnName: 'overViewUrl', dataType: 'VARCHAR(105)' },
        { columnName: 'timeOut', dataType: 'VARCHAR(5)' },
        { columnName: 'attendantData', dataType: 'NVARCHAR(4000)' },
        { columnName: 'countSkip', dataType: 'INTEGER' },
        { columnName: 'checkOverview', dataType: 'INTEGER' },
        { columnName: 'note', dataType: 'NVARCHAR(512)' },
        { columnName: 'province', dataType: 'NVARCHAR(512)' },
        { columnName: 'contactName', dataType: 'NVARCHAR(512)' },
        { columnName: 'mobile', dataType: 'NVARCHAR(256)' },
        { columnName: 'record', dataType: 'INTEGER' },
        { columnName: 'isDoneReport', dataType: 'INTEGER' },
        { columnName: 'subSegment', dataType: 'NVARCHAR(128)' },
        { columnName: 'shopFormat', dataType: 'NVARCHAR(128)' },
        { columnName: 'shopFormatId', dataType: 'INTEGER' },
        { columnName: 'isLockReport', dataType: 'INTEGER' },
        { columnName: 'config', dataType: 'NVARCHAR(512)' },
        { columnName: 'messageLockReport', dataType: 'NVARCHAR(512)' },
        { columnName: 'PRIMARY', dataType: 'KEY(shopId,shiftCode)' },
    ]
}